services:
  undarr:
    image: ghcr.io/mar-tok/undarr:latest
    container_name: undarr
    restart: unless-stopped
    ports:
      - "6545:6545"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - /path/to/media:/media
    environment:
      - PUID=1000
      - PGID=1000
